USE CUSTOMER_DB;

DROP PROCEDURE IF EXISTS tenthousand;

DELIMITER //
CREATE PROCEDURE tenthousand ()
BEGIN
    SELECT CUST_NAME, GRADE FROM customer 
    WHERE OPENING_AMT + RECEIVE_AMT > 10000;
END //
DELIMITER ;

CALL tenthousand();